# Generated by Django 5.2.4 on 2025-09-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_list', 'Can view list of users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
