# Generated by Django 5.2.4 on 2025-09-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='test_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.testrecord'),
        ),
        migrations.AddField(
            model_name='alert',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='inventory.testresult'),
        ),
    ]
