# Generated by Django 5.2.4 on 2025-09-28 13:43

import audit_trail.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the product, e.g., Product001', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'permissions': [('can_view_products', 'Can view product definitions'), ('can_manage_products', 'Can add, edit, delete product definitions')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Grade',
                'verbose_name_plural': 'Product Grades',
                'permissions': [('can_view_product_grades', 'Can view product grade definitions'), ('can_manage_product_grades', 'Can add, edit, delete product grade definitions')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accessible_by_groups', models.ManyToManyField(blank=True, help_text='Groups that have access to perform and view tests in this lab.', related_name='group_accessible_labs', to='auth.group')),
                ('accessible_by_users', models.ManyToManyField(blank=True, help_text='Specific users who have exceptional access to this lab.', related_name='user_accessible_labs', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum (Dropdown)')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('enum_options', models.JSONField(blank=True, help_text='For ENUM type, provide options as a JSON array, e.g., ["Option1", "Option2"]', null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('boolean_true_label', models.CharField(blank=True, help_text="Custom label for the 'true' value, e.g., 'Present', 'Yes'.", max_length=50, null=True)),
                ('boolean_false_label', models.CharField(blank=True, help_text="Custom label for the 'false' value, e.g., 'Absent', 'No'.", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Parameter Definition',
                'verbose_name_plural': 'Parameter Definitions',
                'unique_together': {('content_type', 'object_id', 'name', 'unit')},
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('version_name', models.CharField(help_text="User-defined version, e.g., 'v1.0', '2025 Q4 Update'", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is this the current, active testing yardstick?')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'permissions': [('can_manage_versions', 'Can create, edit, lock, and activate versions')],
                'unique_together': {('product', 'version_name')},
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, editable=False, help_text='Auto-generated unique test record ID, e.g. TR20250731-01', max_length=20, null=True, unique=True)),
                ('batch_no', models.CharField(help_text="The batch number for the sample, e.g., 'A'", max_length=255)),
                ('sample_id', models.CharField(help_text='Identifier for the sample tested. Not unique, as retests will share this ID.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETEST', 'Retest'), ('RETEST_ORDERED', 'Retest Ordered')], default='PENDING', max_length=20)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tests', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_records', to='inventory.lab')),
                ('product_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_records', to='inventory.productgrade')),
                ('retest_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retests', to='inventory.testrecord')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_records', to='inventory.version')),
            ],
            options={
                'verbose_name': 'Test Record',
                'verbose_name_plural': 'Test Records',
                'permissions': [('can_view_test_records', 'Can view test records'), ('can_manage_test_records', 'Can add, edit, delete test records'), ('can_approve_test_records', 'Can approve/reject test records'), ('can_view_all_test_records', 'Can view all test records from all analysts')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='productgrade',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='inventory.version'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('value_string', models.CharField(blank=True, max_length=500, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_values', to='inventory.parameterdefinition')),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='inventory.testrecord')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'unique_together': {('test_record', 'parameter')},
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='productgrade',
            unique_together={('version', 'name')},
        ),
    ]
