# Generated by Django 5.2.4 on 2025-10-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_testrecord_retest_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrecord',
            options={'permissions': [('can_view_test_records', 'Can view test records'), ('can_manage_test_records', 'Can add, edit, delete test records'), ('can_approve_test_records', 'Can approve/reject test records'), ('can_view_all_test_records', 'Can view all test records from all analysts'), ('can_view_quality_trends', 'Can view quality trends graphs')], 'verbose_name': 'Test Record', 'verbose_name_plural': 'Test Records'},
        ),
    ]
