# Generated by Django 5.2.4 on 2025-08-18 07:56

import audit_trail.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.CharField(help_text='A unique identifier for the product, e.g., Product001', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'permissions': [('can_view_products', 'Can view product definitions'), ('can_manage_products', 'Can add, edit, delete product definitions')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Grade',
                'verbose_name_plural': 'Product Grades',
                'permissions': [('can_view_product_grades', 'Can view product grade definitions'), ('can_manage_product_grades', 'Can add, edit, delete product grade definitions')],
                'unique_together': {('product', 'name')},
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum (Dropdown)')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('enum_options', models.JSONField(blank=True, help_text='For ENUM type, provide options as a JSON array, e.g., ["Option1", "Option2"]', null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='The minimum normal value for this parameter.', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='The maximum normal value for this parameter.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='inventory.product')),
                ('product_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='inventory.productgrade')),
            ],
            options={
                'verbose_name': 'Parameter Definition',
                'verbose_name_plural': 'Parameter Definitions',
                'permissions': [('can_view_parameter_definitions', 'Can view parameter definitions'), ('can_manage_parameter_definitions', 'Can add, edit, delete parameter definitions')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, editable=False, help_text='Auto-generated unique test record ID, e.g. TR20250731-01', max_length=20, null=True, unique=True)),
                ('batch_no', models.CharField(help_text="The batch number for the sample, e.g., 'A'", max_length=255)),
                ('sample_id', models.CharField(help_text='Identifier for the sample tested. Not unique, as retests will share this ID.', max_length=255)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETEST', 'Retest')], default='PENDING', max_length=20)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to='inventory.product')),
                ('product_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_records', to='inventory.productgrade')),
                ('retest_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retests', to='inventory.testrecord')),
            ],
            options={
                'verbose_name': 'Test Record',
                'verbose_name_plural': 'Test Records',
                'permissions': [('can_view_test_records', 'Can view test records'), ('can_manage_test_records', 'Can add, edit, delete test records'), ('can_approve_test_records', 'Can approve/reject test records')],
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('value_string', models.CharField(blank=True, max_length=500, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_values', to='inventory.parameterdefinition')),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='inventory.testrecord')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'unique_together': {('test_record', 'parameter')},
            },
            bases=(audit_trail.mixins.AuditableMixin, models.Model),
        ),
    ]
