# Generated by Django 5.2.4 on 2025-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the product, e.g., Product001', max_length=50, unique=True),
        ),
    ]
