# Generated by Django 5.2.4 on 2025-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this the current, active specification for new tests?'),
        ),
    ]
