# Generated by Django 5.2.4 on 2025-08-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefinition',
            name='boolean_false_label',
            field=models.CharField(blank=True, help_text="Custom label for the 'false' value, e.g., 'Absent', 'No'.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameterdefinition',
            name='boolean_true_label',
            field=models.CharField(blank=True, help_text="Custom label for the 'true' value, e.g., 'Present', 'Yes'.", max_length=50, null=True),
        ),
    ]
