# Generated by Django 5.2.4 on 2025-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_specification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked')], default='DRAFT', help_text='DRAFT specs can be edited. LOCKED specs are immutable historical records.', max_length=10),
        ),
        migrations.AlterField(
            model_name='specification',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this the current, active specification for new tests? Only LOCKED specs can be active.'),
        ),
    ]
