# Generated by Django 5.2.4 on 2025-08-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_parameterdefinition_boolean_false_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETEST', 'Retest'), ('RETEST_ORDERED', 'Retest Ordered')], default='PENDING', max_length=20),
        ),
    ]
