# Generated by Django 5.2.4 on 2025-08-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_testrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETEST', 'Retest'), ('RETEST_ORDERED', 'Retest Ordered')], default='PENDING', max_length=20),
        ),
    ]
