# Generated by Django 5.2.4 on 2025-11-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_testrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='The final approval or rejection decision, preserved when closed.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdefinition',
            name='data_type',
            field=models.CharField(choices=[('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum (Dropdown)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='parameterdefinition',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
